const products = [
    {
        name: "Product 1",
        category: "pizzas",
        price: 12.25,
        image: "/images/1.png",
    },
    {
        name: "Product 6",
        category: "burgers",
        price: 10.65,
        image: "/images/6.png",
    },
    {
        name: "Product 2",
        category: "pizzas",
        price: 13.25,
        image: "/images/2.png",
    },
    {
        name: "Product 3",
        category: "pizzas",
        price: 13.95,
        image: "/images/3.png",
    },
    {
        name: "Product 7",
        category: "burgers",
        price: 12.15,
        image: "/images/7.png",
    },
    {
        name: "Product 12",
        category: "drinks",
        price: 12.25,
        image: "/images/12.png",
    },
    {
        name: "Product 4",
        category: "pizzas",
        price: 12.50,
        image: "/images/4.png",
    },
    {
        name: "Product 5",
        category: "pizzas",
        price: 11.85,
        image: "/images/5.png",
    },
    {
        name: "Product 8",
        category: "burgers",
        price: 10.95,
        image: "/images/8.png",
    },
    {
        name: "Product 9",
        category: "burgers",
        price: 12.00,
        image: "/images/9.png",
    },
    ,
    {
        name: "Product 13",
        category: "drinks",
        price: 10.5,
        image: "/images/13.png",
    },
    ,
    {
        name: "Product 10",
        category: "burgers",
        price: 10.00,
        image: "/images/10.png",
    },
    ,
    {
        name: "Product 11",
        category: "burgers",
        price: 10.25,
        image: "/images/11.png",
    },
    ,
    {
        name: "Product 14",
        category: "drinks",
        price: 10.80,
        image: "/images/14.png",
    },
    ,
    {
        name: "Product 15",
        category: "drinks",
        price: 10.70,
        image: "/images/15.png",
    },
    ,
    {
        name: "Product 16",
        category: "drinks",
        price: 10.00,
        image: "/images/16.png",
    },
    ,
    {
        name: "Product 17",
        category: "drinks",
        price: 10.80,
        image: "/images/17.png",
    },
    ,
    {
        name: "Product 18",
        category: "drinks",
        price: 10.40,
        image: "/images/18.png",
    },
    ,
    {
        name: "Product 19",
        category: "drinks",
        price: 10.50,
        image: "/images/19.png",
    },
    ,
    {
        name: "Product 20",
        category: "drinks",
        price: 10.90,
        image: "/images/20.png",
    },
    ,
    {
        name: "Product 21",
        category: "drinks",
        price: 10.20,
        image: "/images/21.png",
    }
]

export default products;